name: Stephen Phyo's CI/CD
on:
  push:
    branches:
    - 'release/v[1-9].[0-9]+'

jobs:
  build_golang:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Railway CLI
      run: npm i -g @railway/cli

    - name: Start Railway
      run: railway up
      env:
       RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}